name: Traduzir Arquivos

on:
  push:
    paths:
      - 'pasta/arquivo_pt.json'  # Ajuste o caminho conforme necessário

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js versão 20
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Passo 3: Configurar Python versão 3.9
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Passo 4: Instalar dependências Python
      - name: Instalar dependências Python
        run: |
          echo "Instalando dependências Python..."
          python -m pip install --upgrade pip
          pip install openai==0.28.0 python-dotenv

      # Passo 5: Verificar versão do openai
      - name: Verificar versão do openai
        run: |
          pip show openai

      # Passo 6: Verificar variável de ambiente OPENAI_API_KEY
      - name: Verificar variável de ambiente OPENAI_API_KEY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY não está definida."
            exit 1
          else
            echo "OPENAI_API_KEY está definida. Primeiros 4 caracteres: ${OPENAI_API_KEY:0:4}****"
          fi

      # Passo 7: Executar o script de tradução
      - name: Executar tradução
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Iniciando o script de tradução..."
          python translate.py
          echo "Script de tradução concluído."

      # Passo 8: Configurar Git para commit
      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Passo 9: Commit e Push das traduções
      - name: Commit e Push das traduções
        run: |
          echo "Adicionando arquivos traduzidos..."
          git add pasta/arquivo_en.json pasta/arquivo_es.json
          echo "Fazendo commit das traduções..."
          git commit -m "Atualizar traduções automáticas" || echo "Nenhuma alteração para commitar"
          echo "Enviando alterações para o repositório remoto..."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
