name: Traduzir Arquivos

on:
  push:
    paths:
      - 'pasta/arquivo_pt.json'  # Ajuste o caminho conforme necessário

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências Python
        run: |
          echo "Instalando dependências Python..."
          python -m pip install --upgrade pip
          pip install openai

      - name: Executar tradução
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Iniciando o script de tradução..."
          python translate.py
          echo "Script de tradução concluído."

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e Push das traduções
        run: |
          echo "Adicionando arquivos traduzidos..."
          git add pasta/arquivo_en.json pasta/arquivo_es.json
          echo "Fazendo commit das traduções..."
          git commit -m "Atualizar traduções automáticas" || echo "Nenhuma alteração para commitar"
          echo "Enviando alterações para o repositório remoto..."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
